/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package doublecode;

import FirebaseProject.FirebaseInitialize;
import login.login.splash;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        FirebaseInitialize tempServer = new FirebaseInitialize();
            tempServer.callFunction();
            splash test = new splash();
            test.main();
            
    }
}
