package NewPost;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author dolya
 */
import FirebaseProject.FirebaseInitialize;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import java.awt.Image;
import java.util.HashMap;
import java.util.Map;
import java.util.UUID;
import java.util.logging.Level;
import java.util.logging.Logger;

public class CreatePost extends javax.swing.JFrame {


    /**
     * Creates new form CreatePost
     */
    
    String username;
    
    public CreatePost() {
        initComponents();
//        ImageIcon myimage = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon-doublecode-350.png")));
//    
//        Image img1 = myimage.getImage();
//        Image img2 = img1.getScaledInstance(logo.getWidth(), logo.getHeight(), Image.SCALE_SMOOTH);
//        ImageIcon i = new ImageIcon(img2);
//    
//        logo.setIcon(i);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        userIcon = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        blockUsername = new javax.swing.JLabel();
        textCreatePost = new javax.swing.JLabel();
        createTitle = new javax.swing.JTextField();
        setType = new javax.swing.JComboBox<>();
        enterPost = new javax.swing.JButton();
        cancelPost = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        createDetail = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(247, 227, 172));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));

        Header.setBackground(new java.awt.Color(247, 176, 105));

        logo.setMaximumSize(new java.awt.Dimension(50, 50));
        logo.setPreferredSize(new java.awt.Dimension(50, 50));

        userIcon.setBackground(new java.awt.Color(224, 216, 244));
        userIcon.setForeground(new java.awt.Color(224, 216, 244));
        userIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-user-30.png"))); // NOI18N
        userIcon.setOpaque(true);

        jPanel9.setBackground(new java.awt.Color(220, 209, 203));

        blockUsername.setFont(new java.awt.Font("Kanit", 0, 18)); // NOI18N
        blockUsername.setForeground(new java.awt.Color(49, 88, 176));
        blockUsername.setText("KarbbPee");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(blockUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(blockUsername)
                .addContainerGap())
        );

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        textCreatePost.setFont(new java.awt.Font("Kanit ExtraBold", 0, 36)); // NOI18N
        textCreatePost.setForeground(new java.awt.Color(247, 176, 105));
        textCreatePost.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textCreatePost.setText("Create Post");
        textCreatePost.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        textCreatePost.setDebugGraphicsOptions(javax.swing.DebugGraphics.FLASH_OPTION);

        createTitle.setBackground(new java.awt.Color(247, 176, 105));
        createTitle.setFont(new java.awt.Font("Kanit SemiBold", 0, 18)); // NOI18N
        createTitle.setForeground(new java.awt.Color(247, 227, 172));
        createTitle.setText(" Title     ");
        createTitle.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 51, 0), null, null, new java.awt.Color(255, 51, 0)));
        createTitle.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                createTitleFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                createTitleFocusLost(evt);
            }
        });

        setType.setBackground(new java.awt.Color(247, 176, 105));
        setType.setFont(new java.awt.Font("Kanit Medium", 0, 18)); // NOI18N
        setType.setForeground(new java.awt.Color(255, 255, 255));
        setType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Game", "Food", "Drama", "Animal", "Sport", "Daily Life", "Study", "Music", "Movie", "Horror", "Love", "Funny", "Religion", "Travel", "Fantasy", "Cartoon" }));
        setType.setAutoscrolls(true);
        setType.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 51, 0), null, null, new java.awt.Color(255, 51, 0)));
        setType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setTypeActionPerformed(evt);
            }
        });

        enterPost.setBackground(new java.awt.Color(198, 221, 244));
        enterPost.setFont(new java.awt.Font("Kanit Medium", 0, 18)); // NOI18N
        enterPost.setText("Post");
        enterPost.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 102, 0), null, null, new java.awt.Color(255, 102, 0)));
        enterPost.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        enterPost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterPostActionPerformed(evt);
            }
        });

        cancelPost.setBackground(new java.awt.Color(198, 221, 244));
        cancelPost.setFont(new java.awt.Font("Kanit Medium", 0, 18)); // NOI18N
        cancelPost.setText("Cancel");
        cancelPost.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 102, 0), null, null, new java.awt.Color(255, 102, 0)));
        cancelPost.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelPost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelPostActionPerformed(evt);
            }
        });

        createDetail.setBackground(new java.awt.Color(222, 222, 222));
        createDetail.setColumns(20);
        createDetail.setFont(new java.awt.Font("Kanit ExtraLight", 1, 18)); // NOI18N
        createDetail.setForeground(new java.awt.Color(150, 150, 150));
        createDetail.setRows(5);
        createDetail.setText("Enter something.     ");
        createDetail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                createDetailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                createDetailFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(createDetail);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(enterPost, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cancelPost, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1156, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(createTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 1017, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(setType, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(72, Short.MAX_VALUE))
            .addComponent(Header, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(textCreatePost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textCreatePost)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(setType))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterPost)
                    .addComponent(cancelPost))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void setUsername(String username) {
        this.username = username;
        this.blockUsername.setText(this.username);
        this.setVisible(true);
    } 
    
    
    
    private void enterPostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterPostActionPerformed
        // TODO add your handling code here:
        if(createTitle.getText().equals(" Title     ")&&createDetail.getText().equals("Enter something.     ")){
            JOptionPane.showMessageDialog(null, "Please enter title and status");
            notify();
        }
        else if(createTitle.getText().equals(" Title     ")){
            JOptionPane.showMessageDialog(null, "Please enter title");
            notify();
        }
        else if(createDetail.getText().equals("Enter something.     ")){
            JOptionPane.showMessageDialog(null, "Please enter status");
            notify();
        }
        
        String authorPost = username;
        String titlePost = CreatePost.createTitle.getText();
        String typePost = CreatePost.setType.getSelectedItem().toString();
        String detailPost = CreatePost.createDetail.getText();
        
        UUID uuidCreate = UUID.randomUUID();
        String uuid = uuidCreate.toString().substring(25);
        String uuidAndTitle = uuid + "-" + titlePost;
        
        Map<String, Object> newPost = new HashMap<>();
        newPost.put("author", authorPost);
        newPost.put("title", titlePost);
        newPost.put("type", typePost);          
        newPost.put("detailPost", detailPost);
        newPost.put("uuid", uuid);
        
        FirebaseInitialize.setPostOnUser(authorPost,  uuidAndTitle, newPost);
        FirebaseInitialize.setPostOnType(typePost, uuidAndTitle, newPost);
        
        Map<String, Object> likes = new HashMap<>();
        likes.put("likes", 0);
        FirebaseInitialize.createLike(typePost, uuid, titlePost, likes);
        
        Map<String, Object> comments = new HashMap<>();      
        FirebaseInitialize.createComment(typePost, uuid, titlePost, comments);
        
        for(int i = 0; i < 10000000; i++){
            
        }
        
        try {
            //user.addUserPost(newPost);
            FirebaseInitialize.presentPost(username,uuid, typePost);
        } catch (Exception ex) {
            Logger.getLogger(CreatePost.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        this.setVisible(false);
    }//GEN-LAST:event_enterPostActionPerformed
   
    private void cancelPostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelPostActionPerformed
        // TODO add your handling code here:
        JFrame frame = new JFrame("Cancel");
        if(JOptionPane.showConfirmDialog(frame, "Confirm cancel post", "Cancel",
                JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION)
        {
            this.setVisible(false);
        }
    }//GEN-LAST:event_cancelPostActionPerformed

    private void createTitleFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_createTitleFocusGained
        // TODO add your handling code here:
        if(createTitle.getText().equals(" Title     ")){
            createTitle.setText("");
            createTitle.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_createTitleFocusGained

    private void createTitleFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_createTitleFocusLost
        // TODO add your handling code here:
        if(createTitle.getText().equals("")){
            createTitle.setText(" Title     ");
            createTitle.setForeground(new Color(247,227,172));
        }
    }//GEN-LAST:event_createTitleFocusLost

    private void createDetailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_createDetailFocusGained
        // TODO add your handling code here:
        if(createDetail.getText().equals("Enter something.     ")){
            createDetail.setText("");
            createDetail.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_createDetailFocusGained

    private void createDetailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_createDetailFocusLost
        // TODO add your handling code here:
        if(createDetail.getText().equals("")){
            createDetail.setText("Enter something.     ");
            createDetail.setForeground(new Color(150,150,150));
        }
    }//GEN-LAST:event_createDetailFocusLost

    private void setTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_setTypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String username) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreatePost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreatePost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreatePost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreatePost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreatePost().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JLabel blockUsername;
    private javax.swing.JButton cancelPost;
    public static javax.swing.JTextArea createDetail;
    public static javax.swing.JTextField createTitle;
    private javax.swing.JButton enterPost;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logo;
    public static javax.swing.JComboBox<String> setType;
    private javax.swing.JLabel textCreatePost;
    private javax.swing.JLabel userIcon;
    // End of variables declaration//GEN-END:variables
}
