package NewPost;


import FirebaseProject.FirebaseInitialize;
import java.awt.Color;
import java.util.concurrent.ExecutionException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


public class Post extends javax.swing.JFrame {

    /**
     * Creates new form Post
     */
    String username;
    String titlePost;
    String typePost;
    String authorPost;
    String detailPost;
    String uuidPost;
    String commentPost;
    Long likePost;
    String checkLike;
    boolean check;
    
    
    public Post() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        showDetail = new javax.swing.JTextArea();
        typeTitle = new javax.swing.JLabel();
        titleTitle = new javax.swing.JLabel();
        authorTitle = new javax.swing.JLabel();
        createComment = new javax.swing.JTextField();
        addLike = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        showTitle = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        showType = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        showAuthor = new javax.swing.JTextPane();
        jPanel2 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        userIcon = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        blockUsername = new javax.swing.JLabel();
        addComment = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        showComment = new javax.swing.JTextArea();
        numLike = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));

        jPanel1.setBackground(new java.awt.Color(247, 227, 172));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));

        showDetail.setEditable(false);
        showDetail.setBackground(new java.awt.Color(222, 222, 224));
        showDetail.setColumns(20);
        showDetail.setFont(new java.awt.Font("Kanit ExtraLight", 1, 18)); // NOI18N
        showDetail.setRows(5);
        showDetail.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 51, 0), null, null, new java.awt.Color(255, 51, 0)));
        jScrollPane1.setViewportView(showDetail);

        typeTitle.setFont(new java.awt.Font("Kanit Medium", 3, 18)); // NOI18N
        typeTitle.setForeground(new java.awt.Color(255, 153, 0));
        typeTitle.setText("Type :");

        titleTitle.setFont(new java.awt.Font("Kanit Medium", 3, 18)); // NOI18N
        titleTitle.setForeground(new java.awt.Color(255, 153, 0));
        titleTitle.setText("Title :");

        authorTitle.setFont(new java.awt.Font("Kanit Medium", 3, 18)); // NOI18N
        authorTitle.setForeground(new java.awt.Color(255, 153, 0));
        authorTitle.setText("Author :");

        createComment.setFont(new java.awt.Font("Kanit Medium", 0, 18)); // NOI18N
        createComment.setForeground(new java.awt.Color(150, 150, 150));
        createComment.setText(" Comment     ");
        createComment.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 51, 0), null, null, new java.awt.Color(255, 0, 0)));
        createComment.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        createComment.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                createCommentFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                createCommentFocusLost(evt);
            }
        });

        addLike.setBackground(new java.awt.Color(255, 51, 0));
        addLike.setFont(new java.awt.Font("Kanit Black", 1, 18)); // NOI18N
        addLike.setForeground(new java.awt.Color(255, 255, 255));
        addLike.setText("<3");
        addLike.setBorder(null);
        addLike.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addLike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLikeActionPerformed(evt);
            }
        });

        showTitle.setEditable(false);
        showTitle.setBackground(new java.awt.Color(247, 176, 105));
        showTitle.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 51, 0), null, null, new java.awt.Color(255, 51, 0)));
        showTitle.setFont(new java.awt.Font("Kanit Medium", 0, 18)); // NOI18N
        showTitle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showTitle.setOpaque(false);
        jScrollPane2.setViewportView(showTitle);

        showType.setEditable(false);
        showType.setBackground(new java.awt.Color(247, 176, 105));
        showType.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 51, 0), null, null, new java.awt.Color(255, 51, 0)));
        showType.setFont(new java.awt.Font("Kanit Medium", 0, 18)); // NOI18N
        showType.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showType.setOpaque(false);
        jScrollPane3.setViewportView(showType);

        showAuthor.setEditable(false);
        showAuthor.setBackground(new java.awt.Color(247, 176, 105));
        showAuthor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 51, 0), null, null, new java.awt.Color(255, 51, 0)));
        showAuthor.setFont(new java.awt.Font("Kanit Medium", 0, 18)); // NOI18N
        showAuthor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showAuthor.setOpaque(false);
        jScrollPane4.setViewportView(showAuthor);

        jPanel2.setBackground(new java.awt.Color(247, 176, 105));
        jPanel2.setPreferredSize(new java.awt.Dimension(612, 83));

        userIcon.setBackground(new java.awt.Color(224, 216, 244));
        userIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-user-30.png"))); // NOI18N
        userIcon.setOpaque(true);

        jPanel9.setBackground(new java.awt.Color(220, 209, 203));

        blockUsername.setFont(new java.awt.Font("Kanit", 0, 18)); // NOI18N
        blockUsername.setForeground(new java.awt.Color(49, 88, 176));
        blockUsername.setText("KarbbPee");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(blockUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(blockUsername)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(861, 861, 861)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        addComment.setBackground(new java.awt.Color(254, 254, 254));
        addComment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/send (1).png"))); // NOI18N
        addComment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCommentActionPerformed(evt);
            }
        });

        showComment.setEditable(false);
        showComment.setColumns(20);
        showComment.setFont(new java.awt.Font("Kanit Medium", 0, 16)); // NOI18N
        showComment.setRows(5);
        jScrollPane5.setViewportView(showComment);

        numLike.setForeground(new java.awt.Color(255, 51, 0));
        numLike.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        numLike.setText("0 Like");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(titleTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(typeTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(authorTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane5)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(addLike, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(numLike, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(32, 32, 32)
                                    .addComponent(createComment, javax.swing.GroupLayout.PREFERRED_SIZE, 930, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(addComment, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titleTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(authorTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(numLike)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addLike, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createComment, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addComment, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1272, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    public void setUsername(String username) {
        this.username = username;
        this.blockUsername.setText(this.username);
        this.setVisible(true);
    } 
    
    
    
    private void createCommentFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_createCommentFocusGained
        // TODO add your handling code here:
        if(createComment.getText().equals(" Comment     ")){
            createComment.setText("");
            createComment.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_createCommentFocusGained

    private void createCommentFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_createCommentFocusLost
        // TODO add your handling code here:
        if(createComment.getText().equals("")){
            createComment.setText(" Comment     ");
            createComment.setForeground(new Color(150,150,150));
        }
    }//GEN-LAST:event_createCommentFocusLost

    private void addLikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLikeActionPerformed
        check = false;
        try {
            // TODO add your handling code here:
           check =  FirebaseInitialize.increaseLike(this.username, this.typePost, this.uuidPost, this.titlePost);
//            check = FirebaseInitialize.increaseLike("noobmaster69", "Sport", "WSd1NeURV1t1alUiyNzA", "Guy love Jok");
        } catch (ExecutionException ex) {
            Logger.getLogger(Post.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(Post.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(check == true){
            this.likePost = this.likePost + 1;
            checkLike = (this.likePost > 1) ? " Likes" : " Like";
            this.numLike.setText(this.likePost + checkLike);
        }
    }//GEN-LAST:event_addLikeActionPerformed

    private void addCommentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCommentActionPerformed
        // TODO add your handling code here:
        if(createComment.getText().equals(" Comment     ")){
            JOptionPane.showMessageDialog(null, "No comment yet");
            notify();
        }
        
        String comment = this.createComment.getText();
        try {
            // TODO add your handling code here:
            FirebaseInitialize.increaseComment(this.username, this.typePost, this.uuidPost, this.titlePost, comment);
//            FirebaseInitialize.increaseComment("noobmaster69", "Sport", "WSd1NeURV1t1alUiyNzA", "Guy love Jok", comment);
        } catch (ExecutionException ex) {
            Logger.getLogger(Post.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(Post.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        this.showComment.setText(this.commentPost + username + " : " + this.createComment.getText() + "\n");
//        this.showComment.setText(this.commentPost + "noobmaster69" + " : " + this.createComment.getText() + "\n");
    }//GEN-LAST:event_addCommentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Post.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Post.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Post.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Post.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Post().setVisible(true);
            }
        });
    }
    
    
    
    public void displayPost(String username, String title, String type, String author, String detail, String uuid, String comment, Long like){
        //Post post = new Post();
        this.titlePost = title;
        this.typePost = type;
        this.authorPost = author;
        this.detailPost = detail;
        this.uuidPost = uuid;
        this.commentPost = comment;
        this.likePost = like;
        this.username = username;
        
        this.blockUsername.setText(this.username);
        this.showTitle.setText(this.titlePost);
        this.showType.setText(this.typePost);
        this.showAuthor.setText(this.authorPost);
        this.showDetail.setText(this.detailPost);
        this.showComment.setText(this.commentPost);
        checkLike = (this.likePost > 1) ? " Likes" : " Like";
        this.numLike.setText(this.likePost + checkLike);
        this.setVisible(true);       
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addComment;
    public static javax.swing.JButton addLike;
    private javax.swing.JLabel authorTitle;
    private javax.swing.JLabel blockUsername;
    public static javax.swing.JTextField createComment;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel numLike;
    private javax.swing.JTextPane showAuthor;
    public javax.swing.JTextArea showComment;
    public javax.swing.JTextArea showDetail;
    private javax.swing.JTextPane showTitle;
    private javax.swing.JTextPane showType;
    private javax.swing.JLabel titleTitle;
    private javax.swing.JLabel typeTitle;
    private javax.swing.JLabel userIcon;
    // End of variables declaration//GEN-END:variables
}
