package NewPost;



import NewPost.*;
import FirebaseProject.FirebaseInitialize;
import java.awt.Color;
import java.util.concurrent.ExecutionException;
import javaswingdev.main.MyPost;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


public class ShowMyPost extends javax.swing.JFrame {

    /**
     * Creates new form ShowMyPost
     */
    MyPost newMyPost;
    int  checkNewMyPost;
    String username;
    String titlePost;
    String typePost;
    String authorPost;
    String detailPost;
    String uuidPost;
    String commentPost;
    Long likePost;
    String checkLike;
    boolean check;
    
    
    public ShowMyPost() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        showTitle = new javax.swing.JTextPane();
        titleTitle = new javax.swing.JLabel();
        typeTitle = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        showType = new javax.swing.JTextPane();
        authorTitle = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        showAuthor = new javax.swing.JTextPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        showDetail = new javax.swing.JTextArea();
        createComment = new javax.swing.JTextField();
        addComment = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        showComment = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        addLike = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        numLike = new javax.swing.JLabel();
        pressRemove = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        userIcon = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        blockUsername2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));

        jPanel1.setBackground(new java.awt.Color(247, 227, 172));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));

        jPanel4.setBackground(new java.awt.Color(255, 255, 243));

        showTitle.setEditable(false);
        showTitle.setBackground(new java.awt.Color(255, 255, 255));
        showTitle.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 51, 0), null, null, new java.awt.Color(255, 51, 0)));
        showTitle.setFont(new java.awt.Font("Kanit Medium", 0, 18)); // NOI18N
        showTitle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showTitle.setOpaque(false);
        jScrollPane2.setViewportView(showTitle);

        titleTitle.setFont(new java.awt.Font("Kanit Medium", 3, 18)); // NOI18N
        titleTitle.setForeground(new java.awt.Color(255, 153, 0));
        titleTitle.setText("Title :");

        typeTitle.setFont(new java.awt.Font("Kanit Medium", 3, 18)); // NOI18N
        typeTitle.setForeground(new java.awt.Color(255, 153, 0));
        typeTitle.setText("Type :");

        showType.setEditable(false);
        showType.setBackground(new java.awt.Color(255, 255, 255));
        showType.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 51, 0), null, null, new java.awt.Color(255, 51, 0)));
        showType.setFont(new java.awt.Font("Kanit Medium", 0, 18)); // NOI18N
        showType.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showType.setOpaque(false);
        jScrollPane3.setViewportView(showType);

        authorTitle.setFont(new java.awt.Font("Kanit Medium", 3, 18)); // NOI18N
        authorTitle.setForeground(new java.awt.Color(255, 153, 0));
        authorTitle.setText("Author :");

        showAuthor.setEditable(false);
        showAuthor.setBackground(new java.awt.Color(255, 255, 255));
        showAuthor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 51, 0), null, null, new java.awt.Color(255, 51, 0)));
        showAuthor.setFont(new java.awt.Font("Kanit Medium", 0, 18)); // NOI18N
        showAuthor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showAuthor.setOpaque(false);
        jScrollPane4.setViewportView(showAuthor);

        showDetail.setEditable(false);
        showDetail.setBackground(new java.awt.Color(255, 255, 255));
        showDetail.setColumns(20);
        showDetail.setFont(new java.awt.Font("Kanit ExtraLight", 1, 18)); // NOI18N
        showDetail.setRows(5);
        showDetail.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 51, 0), null, null, new java.awt.Color(255, 51, 0)));
        jScrollPane1.setViewportView(showDetail);

        createComment.setFont(new java.awt.Font("Kanit Medium", 0, 18)); // NOI18N
        createComment.setForeground(new java.awt.Color(150, 150, 150));
        createComment.setText(" Comment     ");
        createComment.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 51, 0), null, null, new java.awt.Color(255, 0, 0)));
        createComment.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        createComment.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                createCommentFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                createCommentFocusLost(evt);
            }
        });

        addComment.setBackground(new java.awt.Color(217, 238, 255));
        addComment.setForeground(new java.awt.Color(217, 238, 255));
        addComment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/send (1).png"))); // NOI18N
        addComment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCommentActionPerformed(evt);
            }
        });

        showComment.setBackground(new java.awt.Color(247, 255, 232));
        showComment.setColumns(20);
        showComment.setFont(new java.awt.Font("Kanit Medium", 0, 16)); // NOI18N
        showComment.setRows(5);
        jScrollPane5.setViewportView(showComment);

        jPanel5.setBackground(new java.awt.Color(255, 238, 242));

        addLike.setBackground(new java.awt.Color(255, 51, 0));
        addLike.setFont(new java.awt.Font("Kanit Black", 1, 24)); // NOI18N
        addLike.setForeground(new java.awt.Color(255, 255, 255));
        addLike.setText("<3");
        addLike.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(70, 191, 255), 3));
        addLike.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addLike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLikeActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        numLike.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        numLike.setForeground(new java.awt.Color(255, 51, 0));
        numLike.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        numLike.setText("0 Like");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(numLike)
                .addContainerGap(130, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(numLike)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(addLike, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addLike, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pressRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-bin-60.png"))); // NOI18N
        pressRemove.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pressRemove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pressRemoveMousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("Delete your post here...");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-topic-35.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(authorTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(titleTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(typeTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(createComment, javax.swing.GroupLayout.PREFERRED_SIZE, 1027, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addComment, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(9, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pressRemove)
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 1176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(titleTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(authorTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(typeTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(addComment, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(createComment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(5, 5, 5)))
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pressRemove, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(26, 26, 26))
        );

        jPanel2.setBackground(new java.awt.Color(247, 176, 105));
        jPanel2.setPreferredSize(new java.awt.Dimension(612, 83));

        jPanel3.setBackground(new java.awt.Color(247, 211, 186));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 136, 91));
        jLabel1.setText("DOUBLE CODE");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jLabel1)
                .addContainerGap(379, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        userIcon.setBackground(new java.awt.Color(224, 216, 244));
        userIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-user-30.png"))); // NOI18N
        userIcon.setOpaque(true);

        jPanel9.setBackground(new java.awt.Color(220, 209, 203));

        blockUsername2.setFont(new java.awt.Font("Kanit", 0, 18)); // NOI18N
        blockUsername2.setForeground(new java.awt.Color(49, 88, 176));
        blockUsername2.setText("KarbbPee");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(blockUsername2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(blockUsername2)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(userIcon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1272, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 847, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    public void setUsername(String username) {
        this.username = username;
        this.blockUsername2.setText(this.username);
        this.setVisible(true);
    }
    
    
    
    
    private void createCommentFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_createCommentFocusGained
        // TODO add your handling code here:
        if(createComment.getText().equals(" Comment     ")){
            createComment.setText("");
            createComment.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_createCommentFocusGained

    private void createCommentFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_createCommentFocusLost
        // TODO add your handling code here:
        if(createComment.getText().equals("")){
            createComment.setText(" Comment     ");
            createComment.setForeground(new Color(150,150,150));
        }
    }//GEN-LAST:event_createCommentFocusLost

    private void addLikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLikeActionPerformed
        check = false;
        try {
            // TODO add your handling code here:
            check = FirebaseInitialize.increaseLike(this.username, this.typePost, this.uuidPost, this.titlePost);
//            check = FirebaseInitialize.increaseLike("noobmaster69", "Sport", "WSd1NeURV1t1alUiyNzA", "Guy love Jok");
        } catch (ExecutionException ex) {
            Logger.getLogger(ShowMyPost.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(ShowMyPost.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(check == true){
            this.likePost = this.likePost + 1;
            checkLike = (this.likePost > 1) ? " Likes" : " Like";
            this.numLike.setText(this.likePost + checkLike);
        }
    }//GEN-LAST:event_addLikeActionPerformed

    private void addCommentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCommentActionPerformed
        // TODO add your handling code here:
        if(createComment.getText().equals(" Comment     ")){
            JOptionPane.showMessageDialog(null, "No comment yet");
            notify();
        }

        String comment = this.createComment.getText();
        try {
            // TODO add your handling code here:
         FirebaseInitialize.increaseComment(this.username, this.typePost, this.uuidPost, this.titlePost, comment);
//            FirebaseInitialize.increaseComment("noobmaster69", "Sport", "WSd1NeURV1t1alUiyNzA", "Guy love Jok", comment);
        } catch (ExecutionException ex) {
            Logger.getLogger(ShowMyPost.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(ShowMyPost.class.getName()).log(Level.SEVERE, null, ex);
        }

         this.showComment.setText(this.commentPost + username + " : " + this.createComment.getText() + "\n");
//        this.showComment.setText(this.commentPost + "noobmaster69" + " : " + this.createComment.getText() + "\n");
    }//GEN-LAST:event_addCommentActionPerformed

    private void pressRemoveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pressRemoveMousePressed
        JFrame frame = new JFrame("Cancel");
        if(JOptionPane.showConfirmDialog(frame, "Confirm delete post", "Cancel",
                JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION)
        {
            
        
        try {
            // TODO add your handling code here:
            FirebaseInitialize.DeletePost(username, uuidPost, typePost);
            System.out.println("Delete done!");
            newMyPost.refresh();
            
            
            this.dispose();
        } catch (InterruptedException ex) {
            Logger.getLogger(ShowMyPost.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        }
        
        
        
    }//GEN-LAST:event_pressRemoveMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowMyPost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowMyPost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowMyPost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowMyPost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowMyPost().setVisible(true);
            }
        });
    }
    
    //title type author detail
    
    public void displayPost(String username,String title, String type, String author, String detail, String uuid, String comment, Long like, MyPost getMyPost){
     
        this.titlePost = title;
        this.typePost = type;
        this.authorPost = author;
        this.detailPost = detail;
        this.uuidPost = uuid;
        this.commentPost = comment;
        this.likePost = like;
        this.username = username;
        this.newMyPost = getMyPost;
        
        this.blockUsername2.setText(this.username);
        this.showTitle.setText(this.titlePost);
        this.showType.setText(this.typePost);
        this.showAuthor.setText(this.authorPost);
        this.showDetail.setText(this.detailPost);
        this.showComment.setText(this.commentPost);
        checkLike = (this.likePost > 1) ? " Likes" : " Like";
        this.numLike.setText(this.likePost + checkLike);
        this.setVisible(true);       
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addComment;
    public static javax.swing.JButton addLike;
    private javax.swing.JLabel authorTitle;
    private javax.swing.JLabel blockUsername2;
    public static javax.swing.JTextField createComment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel numLike;
    private javax.swing.JLabel pressRemove;
    private javax.swing.JTextPane showAuthor;
    public javax.swing.JTextArea showComment;
    public javax.swing.JTextArea showDetail;
    private javax.swing.JTextPane showTitle;
    private javax.swing.JTextPane showType;
    private javax.swing.JLabel titleTitle;
    private javax.swing.JLabel typeTitle;
    private javax.swing.JLabel userIcon;
    // End of variables declaration//GEN-END:variables
}
